### ISSUE TITLE
Crashes on Xubuntu16.04 with AMD Radeon

### ISSUE THREAD

**Issue by hase-berlin** [Traumflug/Visolate#7]
I think this is the operative word:

```
SIGSEGV (0xb) at pc=0x00007f90948d5823, pid=13282, tid=140258956797696

JRE version: OpenJDK Runtime Environment (8.0_91-b14) (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
Java VM: OpenJDK 64-Bit Server VM (25.91-b14 mixed mode linux-amd64 compressed oops)
Problematic frame:
C  [radeonsi_dri.so+0x256823]
```
pointing to the Radeon driver. (HP Z600 with Radeon 7950, dual monitor)
This crash does not happen on a Thinkpad T420 with Intel graphics.

hase

**Comment by Traumflug** [comment]
First, thanks for trying Visolate.

The crash happens inside the graphics driver, so Visolate can't do much to avoid this. Driver developers might be interested in this bug report.

**Comment by hase-berlin** [comment]
Thought so. 
Hoped you had an idea what triggered the problem and how to avoid it :-)

I'll close the issue as SEP (or PAL in german)

hase
